Add base readme
wpilibsuite/roborio-toolchain pull request #4
Opened 2019-05-31 19:33 UTC by ThadHouse

2019-06-02 13:24 UTC, AustinShalit requested changes

2019-06-02 13:24 UTC, AustinShalit commented on README.md
> +The macOS build must be performed natively on macOS, and has been tested to build correctly on 10.13.To build, just use the `build-linux-tgz.sh` script, which will build the toolchain. The compiler a
```suggestion
The macOS build must be performed natively on macOS, and has been tested to build correctly on 10.13. To build, just use the `build-linux-tgz.sh` script, which will build the toolchain. The compiler archive will be placed in the root directory as `FRC-YEAR-Mac-Toolchain-GccVersion.tar.gz`.
```

2019-06-09 17:23 UTC, ThadHouse commented
@AustinShalit was that it? You're much better at docs then I am.

2019-06-10 02:53 UTC, AustinShalit requested changes
Actually, one more change haha.  But yes... this looks good after this.

2019-06-10 02:53 UTC, AustinShalit commented on README.md
> +This repo uses Docker on linux in order to build the Windows Compiler. To build, just use the `build-windows.sh` script, which will build the toolchain. The compiler archive will be placed in the roo
```suggestion
This repo uses Docker on linux in order to build the Windows Compiler. To build, just use the `build-windows.sh` script, which will build the toolchain. The compiler archive will be placed in the root directory as `FRC-YEAR-Window-Toolchain-GccVersion.zip`. The compiler is a 32 bit executable, and has been tested to work on Windows 7 and newer systems.
```

2019-06-11 00:33 UTC, AustinShalit approved these changes

2019-06-15 01:55 UTC, merged